spring.application.name=challengeDevOps

spring.datasource.url=jdbc:mysql://localhost:3306/challengedevops?useSSL=false&serverTimezone=UTC
spring.datasource.username=cartasso
spring.datasource.password=cartasso

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver